### ISSUE TITLE
[Suggestion] Migrate RMRK2 NFTs to Statemine

### ISSUE THREAD

**Issue by yangwao** [kodadot/grants#32]
Project Description 
---
There are 800k+ items on RMRK2 which been there created as experiment plus bunch of RMRKv1 items. 
Singular decomissined their endpoints for v1 and will do so for v2 in less than 9 months.

Currently these NFTs are only opensource indexed by KodaDot. KodaDot is currently only saviour here, yet maintaining costs could be in future higher and response times of indexer slower. 

I would like to see moving these RMRK2 over to Statemine which would be nice for keeping their longevity, especially for authors. Later easier to index them any available to everyone. 

RMRKv1 - 28465 items for sale, total 98694 items
RMRKv2 - 34659 items for sale,  658848 items (not including canaria collection and other we could not index)

Deliverables
---
Make tool where people in non-custodial mode can migrate their NFTs in easy way. Best if it's webUI, maybe even mobile for migration and working w/o errors and demonstrating functionality and secures migration period of those NFTs to Statemine chain

Reach out
---
Want to work on this? [Come to chat to KodaDot Grants room on Telegram](https://t.me/kodadot_eco/6)

**Comment by roiLeo** [comment]
### Step by step flow

##### Chain A (rmrk2)

1. check collection issuer === creator
2. LIST all nft 0
3. Migrate nft one by one (Start chain B)
4. Don't forget to burn once migrated

##### Chain B (statemine)

1. Create miror collection from Chain A
2. Add newly Minted Nft from chain A (copy)
3. Once minted burn nft on Chain A
5. repeat on all available nfts
6. Transfer owned nft to right account
7. Transfer Collection [Ownership](https://wiki.polkadot.network/docs/learn-assets#creation-and-management)


wdyt @vikiival is this something doable?

**Comment by yangwao** [comment]
Meanwhile 
- https://github.com/kodadot/nft-gallery/issues/7552

**Comment by roiLeo** [comment]
no answers, me sad 😞 

Looks like a part of answer can be found on [nft-migrator](https://github.com/jsidorenko/nft-migrator) but it would be nice to include nft pallet doc.

**Comment by vikiival** [comment]
> no answers, me sad 😞

This one has slipped throgh my notifs, but chain A is almost the same. 
Chain B - you mirror whole collection and either:
Admin will be set to our migrator and it will presign the nfts 
or 
all non-onwed nfts are stored in migrator that will be unlocked once user will burn.  Chceck designs made by @exezbcz. 

If something is unclear I am happy to give more ideas
