### ISSUE TITLE
critical: cannot make waifu

### ISSUE THREAD

**Issue by 7flash** [kodadot/grants#37]
It shows this error on third step of minting:

```
Error: [WAIFU::DO] Unable to CAMPAIGN for reasons Error: D1_ERROR: ERROR 9015: SQL engine error: query error: Error code 2067: A UNIQUE constraint failed (UNIQUE constraint failed: mints_berlin_waifu.address)
```

**Comment by yangwao** [comment]
Hello, this is not the right repository to post this; 
Please open the issue in nft-gallery
- https://github.com/kodadot/nft-gallery/issues/new/choose
Thanks
